#ifndef MUNCHKINLIB_GLOBAL_H
#define MUNCHKINLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MUNCHKINLIB_LIBRARY)
#  define MUNCHKINLIBSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MUNCHKINLIBSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MUNCHKINLIB_GLOBAL_H
